#pragma once
#include <optional>
namespace game
{
	enum class Achievement
	{
		YER_DEAD,
		POOPED_YER_TROUSERS,
		YOU_WIN,
		DISTRACTED_WEREWOLF,
		FLASHED_WYVERN,
		SMITTEN,
		GOT_DRUNK,
		HEAD_BANGER,
		FOURTH_WALL,
		DEATH_BY_WEREWOLF,
		DEATH_BY_WYVERN,
		DEATH_BY_BRAIN_TENTACLE,
		DEATH_BY_IMP,
		DEATH_BY_TROGLODYTE,
		DEATH_BY_BULLY_MINION,
		DEATH_BY_EVIL_BAT,
		DEATH_BY_EVIL_MINION
	};
	enum class Statistic
	{
		GAMES_PLAYED,
		MOVES_MADE,
		TIMES_POOPED,
		TIMES_DIED,
		BEERS_DRUNK,
		COFFEE_DRUNK,
		TIMES_DROPPED_TROU,
		WINE_DRUNK,
		FOOD_EATEN,
		KEYS_USED,
		MAP_FRAGMENTS_FOUND,
		WALLS_BUMPED,
		SOILED_TROUSERS,
		BOOZE_DRUNK,
		DIED_WITH_DIGNITY,
		DIED_WITHOUT_DIGNITY,
		GOT_DRUNK_STAT,
		KILLED_BY_WEREWOLF,
		KILLED_BY_WYVERN,
		KILLED_BY_BRAIN_TENTACLE,
		KILLED_BY_IMP,
		KILLED_BY_TROGLODYTE,
		KILLED_BY_BULLY_MINION,
		KILLED_BY_EVIL_BAT,
		KILLED_BY_EVIL_MINION,
		BROKEN_WALL
	};
}
namespace game::Statistics
{
	void Increment(const game::Statistic&);
	std::optional<int> Read(const game::Statistic&);
}
namespace game::Achievements
{
	void Add(const game::Achievement&);
	void Start();
	bool ShouldRestartApp();
}
